plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_4:module_4_157"))
    implementation(project(":layer_4:module_4_187"))
    implementation(project(":layer_4:module_4_148"))
    implementation(project(":layer_4:module_4_167"))
    implementation(project(":layer_4:module_4_135"))
    implementation(project(":layer_4:module_4_172"))
    implementation(project(":layer_4:module_4_165"))
    implementation(project(":layer_4:module_4_164"))
    implementation(project(":layer_4:module_4_176"))
    implementation(project(":layer_4:module_4_178"))
    implementation(project(":layer_4:module_4_188"))
    implementation(project(":layer_4:module_4_139"))
    implementation(project(":layer_4:module_4_155"))
    implementation(project(":layer_4:module_4_175"))
    implementation(project(":layer_4:module_4_134"))
    implementation(project(":layer_4:module_4_173"))
    implementation(project(":layer_4:module_4_151"))
    implementation(project(":layer_4:module_4_153"))
    implementation(project(":layer_4:module_4_180"))
    implementation(project(":layer_4:module_4_158"))
    implementation(project(":layer_4:module_4_183"))
    implementation(project(":layer_4:module_4_133"))
    implementation(project(":layer_4:module_4_131"))
    implementation(project(":layer_4:module_4_154"))
    implementation(project(":layer_4:module_4_163"))
    implementation(project(":layer_4:module_4_171"))
    implementation(project(":layer_4:module_4_136"))
    implementation(project(":layer_4:module_4_146"))
    implementation(project(":layer_4:module_4_142"))
    implementation(project(":layer_4:module_4_152"))
    implementation(project(":layer_4:module_4_140"))
    implementation(project(":layer_4:module_4_189"))
    implementation(project(":layer_4:module_4_147"))
    implementation(project(":layer_4:module_4_182"))
    implementation(project(":layer_4:module_4_145"))
    implementation(project(":layer_4:module_4_137"))
    implementation(project(":layer_4:module_4_174"))
    implementation(project(":layer_4:module_4_166"))
    implementation(project(":layer_4:module_4_169"))
}
        