plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_4:module_4_150"))
    implementation(project(":layer_4:module_4_164"))
    implementation(project(":layer_4:module_4_143"))
    implementation(project(":layer_4:module_4_142"))
    implementation(project(":layer_4:module_4_152"))
    implementation(project(":layer_4:module_4_184"))
    implementation(project(":layer_4:module_4_190"))
    implementation(project(":layer_4:module_4_168"))
    implementation(project(":layer_4:module_4_148"))
    implementation(project(":layer_4:module_4_159"))
    implementation(project(":layer_4:module_4_165"))
    implementation(project(":layer_4:module_4_163"))
    implementation(project(":layer_4:module_4_179"))
    implementation(project(":layer_4:module_4_132"))
    implementation(project(":layer_4:module_4_149"))
    implementation(project(":layer_4:module_4_180"))
    implementation(project(":layer_4:module_4_187"))
    implementation(project(":layer_4:module_4_175"))
    implementation(project(":layer_4:module_4_140"))
    implementation(project(":layer_4:module_4_141"))
    implementation(project(":layer_4:module_4_162"))
    implementation(project(":layer_4:module_4_133"))
    implementation(project(":layer_4:module_4_166"))
    implementation(project(":layer_4:module_4_171"))
    implementation(project(":layer_4:module_4_135"))
    implementation(project(":layer_4:module_4_191"))
    implementation(project(":layer_4:module_4_176"))
    implementation(project(":layer_4:module_4_186"))
    implementation(project(":layer_4:module_4_147"))
    implementation(project(":layer_4:module_4_178"))
    implementation(project(":layer_4:module_4_188"))
    implementation(project(":layer_4:module_4_170"))
    implementation(project(":layer_4:module_4_137"))
    implementation(project(":layer_4:module_4_138"))
    implementation(project(":layer_4:module_4_145"))
    implementation(project(":layer_4:module_4_183"))
    implementation(project(":layer_4:module_4_157"))
    implementation(project(":layer_4:module_4_160"))
    implementation(project(":layer_4:module_4_189"))
    implementation(project(":layer_4:module_4_172"))
}
        